import comp from "/Users/apple/code/my-docs/src/.vuepress/.temp/pages/zh/platform/1.taixiu（骰宝）.html.vue"
const data = JSON.parse("{\"path\":\"/zh/platform/1.taixiu%EF%BC%88%E9%AA%B0%E5%AE%9D%EF%BC%89.html\",\"title\":\"1.taixiu（骰宝）\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"1.taixiu（骰宝）\",\"icon\":\"fa6-brands:markdown\",\"order\":2,\"category\":[\"使用指南\"],\"tag\":[\"小游戏\"],\"description\":\"游戏说明 该游是一款多人参与的投注类型游戏，玩家可通过对指定区域进行投注，系统根据设定的开奖算法对游戏进行开奖结算。 基本规则 公平性认证 所有结果由 RNG（随机数生成器）系统生成，确保绝对随机与公平 下注目标 预测 三颗骰子 的总点数结果 大（Tài）：总和 11-18 小（Xỉu）：总和 3-10 头奖机制 大极端：总和=18点（如🎲6+6+6...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"1.taixiu（骰宝）\\\",\\\"image\\\":[\\\"https://localhost/images/tx.png\\\",\\\"https://localhost/images/ct/1-jztj.png\\\",\\\"https://localhost/images/ct/1-jsgs.png\\\",\\\"https://localhost/images/ct/1-sljs.png\\\",\\\"https://localhost/images/ct/1-bjjs.png\\\",\\\"https://localhost/images/tx/taixiu-index.png\\\",\\\"https://localhost/images/tx/help-1.png\\\",\\\"https://localhost/images/tx/help-2.png\\\",\\\"https://localhost/images/tx/my.png\\\",\\\"https://localhost/images/tx/qs-1.png\\\",\\\"https://localhost/images/tx/qs-2.png\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"kylin\\\",\\\"url\\\":\\\"https://kylin.io\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://localhost/zh/platform/1.taixiu%EF%BC%88%E9%AA%B0%E5%AE%9D%EF%BC%89.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"蜂巢赢家\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"1.taixiu（骰宝）\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"游戏说明 该游是一款多人参与的投注类型游戏，玩家可通过对指定区域进行投注，系统根据设定的开奖算法对游戏进行开奖结算。 基本规则 公平性认证 所有结果由 RNG（随机数生成器）系统生成，确保绝对随机与公平 下注目标 预测 三颗骰子 的总点数结果 大（Tài）：总和 11-18 小（Xỉu）：总和 3-10 头奖机制 大极端：总和=18点（如🎲6+6+6...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://localhost/images/tx.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"小游戏\"}]]},\"readingTime\":{\"minutes\":3.54,\"words\":1062},\"filePathRelative\":\"zh/platform/1.taixiu（骰宝）.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
